### ISSUE TITLE
Resource profitbricks_loadbalancer should accept list of NIC ids

### ISSUE THREAD

**Issue by jasmingacic** [terraform-providers/terraform-provider-profitbricks#14]
According to ProfitBricks Cloud API documentation https://devops.profitbricks.com/api/cloud/v4/#create-load-balancer `nic_id` should be a list and accept list of string (NIC ids).

**Comment by wojciech12** [comment]
+1
Could you share your workaround? I am strangling to setup LB. Do you use profitbricks CLI?

**Comment by edevenport** [comment]
@wojciech12 As @jasmingacic noted, there is an issue where the `nic_id` should accept a list of NIC IDs rather than a string. We can easily fix this. However, there is a larger issue with the ProfitBricks load balancer feature. When a balanced NIC is assigned, the LAN resource/object changes - essentially creating a new LAN ID. This interferes with Terraform as it attempts to manage and store the infrastructure state. This issue has been reported to ProfitBricks, but it has not yet been fixed as far as I know.

Once we submit a fix for the `nic_id`, you are welcome to further test load balancers with Terraform. If you encounter the above described state problem, then we recommend reporting the issue to ProfitBricks Support.

In the meantime, you may need to manage the load balancers through the CLI or the DCD. Another option might be to see if there is a software load balancer solution (HAProxy, etc.) available as a Terraform module.
